"""add_indexed_documents_table

Revision ID: 7c4e1b90d3a2
Revises: 3f1c2a9d4e5b
Create Date: 2026-08-23

Incremental document indexing (DCL-108): one row per indexed file, keyed by
its workspace-relative path and carrying the content hash that lets an
unchanged file be skipped without ever opening a parser.

Written by hand rather than autogenerated: alembic's autogenerate cannot drive
the async aiosqlite driver this project configures (MissingGreenlet).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c4e1b90d3a2'
down_revision: Union[str, Sequence[str], None] = '3f1c2a9d4e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'indexed_documents',
        sa.Column('path', sa.String(length=1024), nullable=False),
        sa.Column('content_sha256', sa.String(length=64), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('mtime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('doc_type', sa.String(length=32), nullable=False),
        sa.Column('chunk_count', sa.Integer(), nullable=False),
        sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('path'),
    )
    with op.batch_alter_table('indexed_documents', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_indexed_documents_content_sha256'),
            ['content_sha256'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_indexed_documents_indexed_at'), ['indexed_at'], unique=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('indexed_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indexed_documents_indexed_at'))
        batch_op.drop_index(batch_op.f('ix_indexed_documents_content_sha256'))
    op.drop_table('indexed_documents')
